// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubrmlutctxrlwetwxzhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicm1sdXRjdHhybHdldHd4emhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNDE1NzgsImV4cCI6MjA3OTcxNzU3OH0.1_9ZLNx6mqDeHjceZeMznFknV918-CPv5YnDPidOAzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});